"use strict";

export const POLL_YES_NO_DESCRIPTION = "Poll? (y)es (n)o: ";
export const BUILD_YES_NO_DESCRIPTION = "Build? (y)es (n)o: ";
export const FAILED_SCRIPT_DESCRIPTION = "The script has failed. Would you like to try again? (y)es (n)o: ";
export const DIRECTORY_PATH_DESCRIPTION = "Directory path: ";
export const INSTALL_YES_NO_DESCRIPTION = "Install? (y)es (n)o: ";
export const PUBLISH_YES_NO_DESCRIPTION = "Publish? (y)es (n)o: ";
export const FORCED_DEPENDENT_DESCRIPTION = "Forced dependent sub-directory name: ";
export const FORCED_DEPENDENCY_DESCRIPTION = "Forced dependency sub-directory name: ";
export const IGNORED_DEPENDENCY_DESCRIPTION = "Ignored dependency sub-directory name: ";
export const GIT_SHELL_COMMANDS_DESCRIPTION = "Git shell command(s) (leave blank for default): ";
export const POLL_SHELL_COMMANDS_DESCRIPTION = "Poll shell command(s) (leave blank for default): ";
export const SAVE_UPDATES_YES_NO_DESCRIPTION = "Save updates? (y)es (n)o: ";
export const ADD_COMMIT_PUSH_GIT_DESCRIPTION = "Add, commit and push with Git? (y)es (n)o: ";
export const BUILD_SHELL_COMMANDS_DESCRIPTION = "Build shell commands() (leave blank for default): ";
export const INSTALL_SHELL_COMMANDS_DESCRIPTION = "Install shell commands() (leave blank for default): ";
export const PUBLISH_SHELL_COMMANDS_DESCRIPTION = "Publish shell commands() (leave blank for default): ";
export const SPECIFY_DIRECTORY_TO_REMOVE_DESCRIPTION = "Specify a directory to remove: ";
export const SPECIFY_IGNORED_DEPENDENCY_TO_REMOVE_DESCRIPTION = "Specify an ignored dependency to remove: ";
export const SPECIFY_FORCED_DEPENDENCY_RELATION_TO_REMOVE_DESCRIPTION = "Specify a forced dependency relation to remove.";
